# Matrix and Vectors

In [1]:
import pandas as pd
import numpy as np

In [3]:
from numpy import array
a=array([[1,2,3],[4,5,6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [4]:
a=array([[1,2,3],[4,5,6]])
b=array([[1,2,3],[4,5,6]])
print(a+b)

[[ 2  4  6]
 [ 8 10 12]]


In [5]:
print(a-b)

[[0 0 0]
 [0 0 0]]


In [6]:
print(a*b)

[[ 1  4  9]
 [16 25 36]]


In [7]:
print(a/b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
from numpy import *
wd=array([['mon',1,2,3],
['tue',4,5,6],
['wed',3,2,1],
['thu',6,4,3]])
print(wd)

[['mon' '1' '2' '3']
 ['tue' '4' '5' '6']
 ['wed' '3' '2' '1']
 ['thu' '6' '4' '3']]


In [16]:
print(wd[1])

['tue' '4' '5' '6']


In [17]:
print(wd[1][2])

5


In [19]:
wd_a=append(wd,[['fri',3,6,9]],0)
print(wd_a)

[['mon' '1' '2' '3']
 ['tue' '4' '5' '6']
 ['wed' '3' '2' '1']
 ['thu' '6' '4' '3']
 ['fri' '3' '6' '9']]


In [32]:
wd_b=insert(wd,[2],[[4],[3],[2],[7]],1)
print(wd_b)

[['mon' '1' '4' '2' '3']
 ['tue' '4' '3' '5' '6']
 ['wed' '3' '2' '2' '1']
 ['thu' '6' '7' '4' '3']]
